### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by Rakesh9100** [opencodeiiita/CalcDiverse#1]
Add a good Contact Page.

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by Rakesh9100** [comment]
Assigned to both of you @kushal7201 @Jarviss77 
Go ahead!! Best one will be merged!

**Comment by sanju26honey** [comment]
Claim

**Comment by Rakesh9100** [comment]
Go ahead!! Best one will be merged!

**Comment by Rakesh9100** [comment]
Go ahead!! Best one will be merged!

**Comment by gautamkhokhar0001** [comment]
claim

**Comment by Shivangi015** [comment]
hey @Rakesh9100 , please assign me this task as this is open now, I can make a good contact page

**Comment by Mannxxx** [comment]
Claim

Issue #1

Completed, added contact page
