### ISSUE TITLE
2D Shapes Calculator

### ISSUE THREAD

**Issue by Rakesh9100** [opencodeiiita/CalcDiverse#2]
Add a Calculator that calculates the perimeter and area of 2D shapes.

**Comment by chiragmalik2612** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by Rakesh9100** [comment]
Assigning to all of you! Best one will be merged!!

**Comment by sanju26honey** [comment]
Claim

**Comment by Rakesh9100** [comment]
Proceed! Best one will be merged!!

**Comment by gautamkhokhar0001** [comment]
claim

**Comment by PrathamJain2601** [comment]
Rakesh sir do we need to claim the issue first and then proceed or I can start working on the issue and create a pull request right away?

**Comment by Rakesh9100** [comment]
Are you contributing for Opencode @PrathamJain2601 
If yes, you can create your PR right away!!

**Comment by Mannxxx** [comment]
Claim
